// Package metrics provides Prometheus instrumentation for the RTVortex API server.
//
// All counters, histograms and gauges are declared here so that every other
// package can import metrics and call the recording helpers without pulling in
// the full prometheus API surface.
package metrics

import (
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// ── Namespace / Subsystems ──────────────────────────────────────────────────

const ns = "rtvortex"

// ── HTTP Metrics ────────────────────────────────────────────────────────────

var (
	// HTTPRequestsTotal counts every HTTP request handled by the server.
	HTTPRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "http",
		Name:      "requests_total",
		Help:      "Total HTTP requests by method, path pattern, and status code.",
	}, []string{"method", "path", "status"})

	// HTTPRequestDuration observes request latency in seconds.
	HTTPRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: ns,
		Subsystem: "http",
		Name:      "request_duration_seconds",
		Help:      "HTTP request duration in seconds.",
		Buckets:   prometheus.DefBuckets,
	}, []string{"method", "path", "status"})

	// HTTPRequestsInFlight tracks how many requests are being processed right now.
	HTTPRequestsInFlight = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: ns,
		Subsystem: "http",
		Name:      "requests_in_flight",
		Help:      "Number of HTTP requests currently being processed.",
	})
)

// ── Review Pipeline Metrics ─────────────────────────────────────────────────

var (
	// ReviewPipelineTotal counts completed (or failed) pipeline runs.
	ReviewPipelineTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "review",
		Name:      "pipeline_total",
		Help:      "Total review pipeline executions by status (completed, failed).",
	}, []string{"status"})

	// ReviewPipelineDuration observes pipeline execution time.
	ReviewPipelineDuration = promauto.NewHistogram(prometheus.HistogramOpts{
		Namespace: ns,
		Subsystem: "review",
		Name:      "pipeline_duration_seconds",
		Help:      "Review pipeline execution duration in seconds.",
		Buckets:   []float64{1, 5, 10, 30, 60, 120, 300, 600},
	})

	// ReviewCommentsTotal counts comments generated by reviews.
	ReviewCommentsTotal = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "review",
		Name:      "comments_total",
		Help:      "Total review comments generated.",
	})

	// ReviewFilesAnalyzed counts files analyzed across all reviews.
	ReviewFilesAnalyzed = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "review",
		Name:      "files_analyzed_total",
		Help:      "Total files analyzed across all review runs.",
	})
)

// ── Engine (gRPC) Metrics ───────────────────────────────────────────────────

var (
	// EngineGRPCRequestsTotal counts gRPC calls to the C++ engine.
	EngineGRPCRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "engine",
		Name:      "grpc_requests_total",
		Help:      "Total gRPC requests to the RTVortex C++ engine by method and status.",
	}, []string{"method", "status"})

	// EngineGRPCDuration observes gRPC call latency.
	EngineGRPCDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: ns,
		Subsystem: "engine",
		Name:      "grpc_duration_seconds",
		Help:      "gRPC call duration to the engine in seconds.",
		Buckets:   []float64{0.01, 0.05, 0.1, 0.5, 1, 5, 10, 30, 60, 120},
	}, []string{"method"})

	// EnginePoolHealthy reports whether the gRPC pool has at least one ready conn.
	EnginePoolHealthy = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: ns,
		Subsystem: "engine",
		Name:      "pool_healthy",
		Help:      "1 if the engine gRPC pool has at least one healthy connection, 0 otherwise.",
	})

	// EngineReconnectsTotal counts pool reconnection attempts.
	EngineReconnectsTotal = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "engine",
		Name:      "reconnects_total",
		Help:      "Total number of gRPC connection reconnection attempts.",
	})
)

// ── LLM Metrics ─────────────────────────────────────────────────────────────

var (
	// LLMRequestsTotal counts completion requests per provider/model.
	LLMRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "llm",
		Name:      "requests_total",
		Help:      "Total LLM completion requests by provider, model, and status.",
	}, []string{"provider", "model", "status"})

	// LLMRequestDuration observes LLM call latency.
	LLMRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: ns,
		Subsystem: "llm",
		Name:      "request_duration_seconds",
		Help:      "LLM completion request duration in seconds.",
		Buckets:   []float64{0.5, 1, 2, 5, 10, 30, 60, 120},
	}, []string{"provider", "model"})

	// LLMTokensUsed tracks token consumption.
	LLMTokensUsed = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "llm",
		Name:      "tokens_used_total",
		Help:      "Total LLM tokens consumed by provider and type (prompt, completion).",
	}, []string{"provider", "type"})
)

// ── WebSocket Metrics ───────────────────────────────────────────────────────

var (
	// WSConnectionsActive tracks active WebSocket connections.
	WSConnectionsActive = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: ns,
		Subsystem: "ws",
		Name:      "connections_active",
		Help:      "Number of active WebSocket connections.",
	})

	// WSMessagesTotal counts WebSocket messages sent.
	WSMessagesTotal = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "ws",
		Name:      "messages_sent_total",
		Help:      "Total WebSocket messages sent to clients.",
	})
)

// ── Rate Limiter Metrics ────────────────────────────────────────────────────

var (
	// RateLimitRejectionsTotal counts rejected requests.
	RateLimitRejectionsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "ratelimit",
		Name:      "rejections_total",
		Help:      "Total requests rejected by the rate limiter by limit name.",
	}, []string{"limit"})
)

// ── Auth Metrics ────────────────────────────────────────────────────────────

var (
	// AuthAttemptsTotal counts login attempts.
	AuthAttemptsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "auth",
		Name:      "attempts_total",
		Help:      "Total authentication attempts by provider and result.",
	}, []string{"provider", "result"})
)

// ── Keychain Vault Metrics ──────────────────────────────────────────────────

var (
	// KeychainOpsTotal counts keychain operations by type and result.
	KeychainOpsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "keychain",
		Name:      "operations_total",
		Help:      "Total keychain operations by operation type and result (ok, error).",
	}, []string{"operation", "result"})

	// KeychainOpDuration observes keychain operation latency.
	KeychainOpDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: ns,
		Subsystem: "keychain",
		Name:      "operation_duration_seconds",
		Help:      "Keychain operation duration in seconds.",
		Buckets:   []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5},
	}, []string{"operation"})

	// KeychainSecretsGauge tracks the total number of active secrets.
	KeychainSecretsGauge = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: ns,
		Subsystem: "keychain",
		Name:      "secrets_active",
		Help:      "Current number of active secrets in the keychain across all users.",
	})

	// KeychainEncryptionDuration observes encryption/decryption latency specifically.
	KeychainEncryptionDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: ns,
		Subsystem: "keychain",
		Name:      "encryption_duration_seconds",
		Help:      "Duration of encryption and decryption operations.",
		Buckets:   []float64{0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1},
	}, []string{"operation"}) // "encrypt" or "decrypt"

	// KeychainKeyRotationsTotal counts key rotation events.
	KeychainKeyRotationsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "keychain",
		Name:      "key_rotations_total",
		Help:      "Total key rotation events by result.",
	}, []string{"result"})

	// KeychainSyncTotal counts sync negotiation requests.
	KeychainSyncTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "keychain",
		Name:      "sync_total",
		Help:      "Total sync negotiation requests by result.",
	}, []string{"result"})

	// KeychainRecoveryTotal counts recovery attempts.
	KeychainRecoveryTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: ns,
		Subsystem: "keychain",
		Name:      "recovery_total",
		Help:      "Total recovery attempts by result.",
	}, []string{"result"})
)

// ── Recording Helpers ───────────────────────────────────────────────────────

// RecordHTTPRequest records an HTTP request's metrics.
func RecordHTTPRequest(method, path string, statusCode int, duration time.Duration) {
	status := strconv.Itoa(statusCode)
	HTTPRequestsTotal.WithLabelValues(method, path, status).Inc()
	HTTPRequestDuration.WithLabelValues(method, path, status).Observe(duration.Seconds())
}

// RecordEngineCall records a gRPC call to the engine.
func RecordEngineCall(method, status string, duration time.Duration) {
	EngineGRPCRequestsTotal.WithLabelValues(method, status).Inc()
	EngineGRPCDuration.WithLabelValues(method).Observe(duration.Seconds())
}

// RecordLLMRequest records an LLM completion request.
func RecordLLMRequest(provider, model, status string, duration time.Duration, promptTokens, completionTokens int) {
	LLMRequestsTotal.WithLabelValues(provider, model, status).Inc()
	LLMRequestDuration.WithLabelValues(provider, model).Observe(duration.Seconds())
	if promptTokens > 0 {
		LLMTokensUsed.WithLabelValues(provider, "prompt").Add(float64(promptTokens))
	}
	if completionTokens > 0 {
		LLMTokensUsed.WithLabelValues(provider, "completion").Add(float64(completionTokens))
	}
}

// RecordPipelineComplete records a review pipeline completion.
func RecordPipelineComplete(status string, duration time.Duration, commentsCount, filesCount int) {
	ReviewPipelineTotal.WithLabelValues(status).Inc()
	ReviewPipelineDuration.Observe(duration.Seconds())
	ReviewCommentsTotal.Add(float64(commentsCount))
	ReviewFilesAnalyzed.Add(float64(filesCount))
}

// RecordKeychainOp records a keychain operation's outcome and latency.
func RecordKeychainOp(operation, result string, duration time.Duration) {
	KeychainOpsTotal.WithLabelValues(operation, result).Inc()
	KeychainOpDuration.WithLabelValues(operation).Observe(duration.Seconds())
}

// RecordKeychainEncryption records encryption or decryption latency.
func RecordKeychainEncryption(op string, duration time.Duration) {
	KeychainEncryptionDuration.WithLabelValues(op).Observe(duration.Seconds())
}

// RecordKeychainKeyRotation records a key rotation event.
func RecordKeychainKeyRotation(result string) {
	KeychainKeyRotationsTotal.WithLabelValues(result).Inc()
}

// RecordKeychainSync records a sync negotiation event.
func RecordKeychainSync(result string) {
	KeychainSyncTotal.WithLabelValues(result).Inc()
}

// RecordKeychainRecovery records a recovery attempt.
func RecordKeychainRecovery(result string) {
	KeychainRecoveryTotal.WithLabelValues(result).Inc()
}

// SetKeychainSecretsGauge updates the active secrets gauge.
func SetKeychainSecretsGauge(count float64) {
	KeychainSecretsGauge.Set(count)
}
