// Package engine — Cross-Repo gRPC Client
//
// This file adds typed Go client methods for the CrossRepoService defined
// in engine.proto. The underlying gRPC stub is generated by protoc into
// internal/engine/pb/engine_grpc.pb.go.
//
// The Go server's crossrepo.Authorizer validates every request BEFORE
// calling these methods — the engine trusts the repo ID lists it receives.
package engine

import (
	"context"
	"fmt"
	"io"
	"time"

	pb "github.com/AuralithAI/rtvortex-server/internal/engine/pb"
)

// ── Domain types for Cross-Repo RPCs ────────────────────────────────────────

// RepoManifestResult holds the structural manifest for a single repo.
type RepoManifestResult struct {
	Found           bool
	RepoID          string
	RepoRoot        string
	PrimaryLanguage string
	BuildSystem     string
	RepoType        string
	Targets         []BuildTarget
	ModuleToFiles   map[string][]string
}

// BuildTarget is a build artifact (library, executable, module, etc.).
type BuildTarget struct {
	Name        string
	Type        string
	SourceGlobs []string
}

// CrossRepoDependency is a single cross-repo dependency edge.
type CrossRepoDependency struct {
	SourceRepoID   string
	SourceFile     string
	SourceSymbol   string
	TargetRepoID   string
	TargetFile     string
	TargetSymbol   string
	DependencyType string
	Confidence     float32
}

// CrossRepoDepsResult is the result of GetCrossRepoDependencies.
type CrossRepoDepsResult struct {
	Dependencies []CrossRepoDependency
	TotalEdges   uint32
}

// DepGraphNode is a node in the org-level dependency graph.
type DepGraphNode struct {
	ID       string
	RepoID   string
	Label    string
	NodeType string
	Language string
	RepoType string
	Metadata map[string]string
}

// DepGraphEdge is an edge in the org-level dependency graph.
type DepGraphEdge struct {
	SourceNodeID string
	TargetNodeID string
	EdgeType     string
	Weight       float32
	Metadata     map[string]string
}

// DepGraphResult is the result of BuildDependencyGraph.
type DepGraphResult struct {
	Success      bool
	Message      string
	ReposScanned uint32
	TotalNodes   uint32
	TotalEdges   uint32
	Nodes        []DepGraphNode
	Edges        []DepGraphEdge
}

// FederatedChunk is a context chunk with cross-repo attribution.
type FederatedChunk struct {
	RepoID          string
	RepoName        string
	Chunk           ContextChunk
	NormalizedScore float32
	RawScore        float32
}

// FederatedSearchResult is the result of FederatedSearch.
type FederatedSearchResult struct {
	Chunks  []FederatedChunk
	Metrics *FederatedSearchMetrics
}

// FederatedSearchMetrics contains timing and attribution stats.
type FederatedSearchMetrics struct {
	ReposSearched     uint32
	ReposFailed       uint32
	TotalCandidates   uint32
	TotalSearchTimeMs uint64
	PerRepoTimeMs     map[string]uint64
	PerRepoResults    map[string]uint32
	NormalizationUsed string
}

// FederatedSearchConfig controls the federated search behaviour.
type FederatedSearchConfig struct {
	SearchConfig
	MaxTotalResults    uint32
	MaxConcurrent      uint32
	ScoreNormalization string // "min_max", "z_score", "none"
}

// ── Cross-Repo stub ─────────────────────────────────────────────────────────

// crossRepoStub returns a fresh CrossRepoService client from the pool.
// The CrossRepoService shares the same gRPC channel as EngineService.
func (c *Client) crossRepoStub() pb.CrossRepoServiceClient {
	return pb.NewCrossRepoServiceClient(c.pool.GetConn())
}

// ──  Manifest & Dependency Graph ──────────────────────────────────

// GetRepoManifest retrieves the structural manifest for a repo.
func (c *Client) GetRepoManifest(ctx context.Context, repoID string) (*RepoManifestResult, error) {
	ctx, cancel := c.ctx(ctx)
	defer cancel()

	resp, err := c.crossRepoStub().GetRepoManifest(ctx, &pb.RepoManifestRequest{
		RepoId: repoID,
	})
	if err != nil {
		return nil, fmt.Errorf("get repo manifest: %w", err)
	}

	result := &RepoManifestResult{Found: resp.Found}
	if resp.Found && resp.Manifest != nil {
		m := resp.Manifest
		result.RepoID = m.RepoId
		result.RepoRoot = m.RepoRoot
		result.PrimaryLanguage = m.PrimaryLanguage
		result.BuildSystem = m.BuildSystem
		result.RepoType = m.RepoType.String()

		for _, t := range m.Targets {
			result.Targets = append(result.Targets, BuildTarget{
				Name:        t.Name,
				Type:        t.Type,
				SourceGlobs: t.SourceGlobs,
			})
		}

		result.ModuleToFiles = make(map[string][]string, len(m.ModuleToFiles))
		for k, v := range m.ModuleToFiles {
			result.ModuleToFiles[k] = v.Files
		}
	}
	return result, nil
}

// GetCrossRepoDependencies resolves inter-repo import/dependency edges.
func (c *Client) GetCrossRepoDependencies(
	ctx context.Context,
	sourceRepoID string,
	targetRepoIDs []string,
	maxDepth uint32,
) (*CrossRepoDepsResult, error) {
	ctx, cancel := c.ctx(ctx)
	defer cancel()

	resp, err := c.crossRepoStub().GetCrossRepoDependencies(ctx, &pb.CrossRepoDepsRequest{
		SourceRepoId:  sourceRepoID,
		TargetRepoIds: targetRepoIDs,
		MaxDepth:      maxDepth,
	})
	if err != nil {
		return nil, fmt.Errorf("get cross-repo deps: %w", err)
	}

	result := &CrossRepoDepsResult{TotalEdges: resp.TotalEdges}
	for _, d := range resp.Dependencies {
		result.Dependencies = append(result.Dependencies, CrossRepoDependency{
			SourceRepoID:   d.SourceRepoId,
			SourceFile:     d.SourceFile,
			SourceSymbol:   d.SourceSymbol,
			TargetRepoID:   d.TargetRepoId,
			TargetFile:     d.TargetFile,
			TargetSymbol:   d.TargetSymbol,
			DependencyType: d.DependencyType,
			Confidence:     d.Confidence,
		})
	}
	return result, nil
}

// BuildDependencyGraph constructs the org-level dependency graph.
func (c *Client) BuildDependencyGraph(
	ctx context.Context,
	orgID string,
	repoIDs []string,
	forceRescan bool,
) (*DepGraphResult, error) {
	// Use a longer timeout for graph builds.
	ctx, cancel := context.WithTimeout(ctx, 5*time.Minute)
	defer cancel()

	resp, err := c.crossRepoStub().BuildDependencyGraph(ctx, &pb.BuildDepGraphRequest{
		OrgId:       orgID,
		RepoIds:     repoIDs,
		ForceRescan: forceRescan,
	})
	if err != nil {
		return nil, fmt.Errorf("build dependency graph: %w", err)
	}

	result := &DepGraphResult{
		Success:      resp.Success,
		Message:      resp.Message,
		ReposScanned: resp.ReposScanned,
		TotalNodes:   resp.TotalNodes,
		TotalEdges:   resp.TotalEdges,
	}

	for _, n := range resp.Nodes {
		result.Nodes = append(result.Nodes, DepGraphNode{
			ID:       n.Id,
			RepoID:   n.RepoId,
			Label:    n.Label,
			NodeType: n.NodeType,
			Language: n.Language,
			RepoType: n.RepoType.String(),
			Metadata: n.Metadata,
		})
	}

	for _, e := range resp.Edges {
		result.Edges = append(result.Edges, DepGraphEdge{
			SourceNodeID: e.SourceNodeId,
			TargetNodeID: e.TargetNodeId,
			EdgeType:     e.EdgeType,
			Weight:       e.Weight,
			Metadata:     e.Metadata,
		})
	}

	return result, nil
}

// ──  Federated Search ─────────────────────────────────────────────

// FederatedSearch fans out a query across multiple repo indices.
func (c *Client) FederatedSearch(
	ctx context.Context,
	query string,
	repoIDs []string,
	touchedSymbols []string,
	cfg FederatedSearchConfig,
) (*FederatedSearchResult, error) {
	ctx, cancel := c.ctx(ctx)
	defer cancel()

	resp, err := c.crossRepoStub().FederatedSearch(ctx, &pb.FederatedSearchRequest{
		Query:          query,
		RepoIds:        repoIDs,
		TouchedSymbols: touchedSymbols,
		Config: &pb.SearchConfig{
			TopK:             cfg.TopK,
			LexicalWeight:    cfg.LexicalWeight,
			VectorWeight:     cfg.VectorWeight,
			GraphExpandDepth: cfg.GraphExpandDepth,
			FileFilters:      cfg.FileFilters,
			LanguageFilters:  cfg.LanguageFilters,
		},
		MaxTotalResults:    cfg.MaxTotalResults,
		MaxConcurrent:      cfg.MaxConcurrent,
		ScoreNormalization: cfg.ScoreNormalization,
	})
	if err != nil {
		return nil, fmt.Errorf("federated search: %w", err)
	}

	return convertFederatedSearchResponse(resp), nil
}

// FederatedSearchStream returns chunks from multiple repos as they are found.
func (c *Client) FederatedSearchStream(
	ctx context.Context,
	query string,
	repoIDs []string,
	touchedSymbols []string,
	cfg FederatedSearchConfig,
	onChunk func(FederatedChunk),
) error {
	ctx, cancel := c.ctx(ctx)
	defer cancel()

	stream, err := c.crossRepoStub().FederatedSearchStream(ctx, &pb.FederatedSearchRequest{
		Query:          query,
		RepoIds:        repoIDs,
		TouchedSymbols: touchedSymbols,
		Config: &pb.SearchConfig{
			TopK:             cfg.TopK,
			LexicalWeight:    cfg.LexicalWeight,
			VectorWeight:     cfg.VectorWeight,
			GraphExpandDepth: cfg.GraphExpandDepth,
			FileFilters:      cfg.FileFilters,
			LanguageFilters:  cfg.LanguageFilters,
		},
		MaxTotalResults:    cfg.MaxTotalResults,
		MaxConcurrent:      cfg.MaxConcurrent,
		ScoreNormalization: cfg.ScoreNormalization,
	})
	if err != nil {
		return fmt.Errorf("federated search stream: %w", err)
	}

	for {
		chunk, err := stream.Recv()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return fmt.Errorf("federated search stream recv: %w", err)
		}
		onChunk(convertFederatedChunk(chunk))
	}
}

// ── Converters ──────────────────────────────────────────────────────────────

func convertFederatedSearchResponse(resp *pb.FederatedSearchResponse) *FederatedSearchResult {
	result := &FederatedSearchResult{}

	for _, c := range resp.Chunks {
		result.Chunks = append(result.Chunks, convertFederatedChunk(c))
	}

	if resp.Metrics != nil {
		m := resp.Metrics
		result.Metrics = &FederatedSearchMetrics{
			ReposSearched:     m.ReposSearched,
			ReposFailed:       m.ReposFailed,
			TotalCandidates:   m.TotalCandidates,
			TotalSearchTimeMs: m.TotalSearchTimeMs,
			PerRepoTimeMs:     m.PerRepoTimeMs,
			PerRepoResults:    m.PerRepoResults,
			NormalizationUsed: m.NormalizationUsed,
		}
	}

	return result
}

func convertFederatedChunk(c *pb.FederatedContextChunk) FederatedChunk {
	fc := FederatedChunk{
		RepoID:          c.RepoId,
		RepoName:        c.RepoName,
		NormalizedScore: c.NormalizedScore,
		RawScore:        c.RawScore,
	}
	if c.Chunk != nil {
		fc.Chunk = convertChunk(c.Chunk)
	}
	return fc
}
