"""Async gRPC client for the C++ RTVortex engine.

Provides semantic search, file-content retrieval, and index-status queries
against the engine process.  Proto stubs are lazy-loaded so the module can
be imported even when ``make proto-python`` has not been run yet (useful for
IDE autocompletion and unit testing with mocks).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import grpc

from .agents_config import get_config

logger = logging.getLogger(__name__)

# Proto-generated stubs will be imported at runtime from the proto/ directory.
# For now we use dynamic imports to avoid hard dependency on generated code.
_pb2 = None
_pb2_grpc = None


def _ensure_stubs():
    """Lazy-load the protobuf/gRPC stubs generated by ``make proto-python``.

    Raises:
        ImportError: If the stubs have not been generated yet.
    """
    global _pb2, _pb2_grpc
    if _pb2 is None:
        try:
            from .proto import engine_pb2 as pb2
            from .proto import engine_pb2_grpc as pb2_grpc
            _pb2 = pb2
            _pb2_grpc = pb2_grpc
        except ImportError:
            logger.warning("Proto stubs not found — engine gRPC calls will fail. "
                           "Run 'make proto' to generate them.")
            raise


class EngineClient:
    """Async gRPC client for the C++ RTVortex engine.

    Call :meth:`connect` once at startup.  All RPC methods are ``async`` and
    safe to call concurrently from multiple agent coroutines — gRPC channels
    multiplex over a single HTTP/2 connection.
    """

    def __init__(self, host: str = "", port: int = 0):
        cfg = get_config()
        self.host = host or cfg.engine_host
        self.port = port or cfg.engine_port
        self._tls = cfg.engine_tls
        self._cert_chain = cfg.engine_cert_chain
        self._private_key = cfg.engine_private_key
        self._trust_certs = cfg.engine_trust_certs
        self._channel: grpc.aio.Channel | None = None
        self._stub = None

    # ------------------------------------------------------------------
    # TLS helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _read_pem(path: str) -> bytes | None:
        """Read a PEM file, returning ``None`` if the path is empty or missing."""
        if not path:
            return None
        p = Path(path)
        if not p.is_file():
            logger.warning("TLS file not found: %s", path)
            return None
        return p.read_bytes()

    def _build_channel_credentials(self) -> grpc.ChannelCredentials:
        """Construct gRPC channel credentials mirroring the Go engine pool.

        * ``trust_certs`` (CA)    → verify the engine's server certificate.
        * ``cert_chain`` + ``private_key`` → mTLS client identity.

        Falls back to default system roots when no custom CA is configured.
        """
        ca_pem = self._read_pem(self._trust_certs)
        cert_pem = self._read_pem(self._cert_chain)
        key_pem = self._read_pem(self._private_key)

        if ca_pem:
            logger.info("Engine TLS: loaded CA certificate (%s)", self._trust_certs)
        if cert_pem and key_pem:
            logger.info("Engine TLS: loaded client certificate for mTLS (%s)",
                        self._cert_chain)
        elif self._cert_chain or self._private_key:
            logger.warning("Engine TLS: client cert or key missing — "
                           "connecting without mTLS client identity")
            cert_pem = None
            key_pem = None

        return grpc.ssl_channel_credentials(
            root_certificates=ca_pem,
            private_key=key_pem,
            certificate_chain=cert_pem,
        )

    async def connect(self) -> None:
        """Establish the gRPC channel.

        Uses a secure channel when ``negotiation-type`` in ``rtserverprops.xml``
        is ``TLS`` or ``mTLS``, and an insecure channel for ``PLAINTEXT``.
        """
        target = f"{self.host}:{self.port}"
        channel_opts = [
            ("grpc.max_receive_message_length", 64 * 1024 * 1024),
            ("grpc.max_send_message_length", 64 * 1024 * 1024),
        ]
        if self._tls:
            self._channel = grpc.aio.secure_channel(
                target,
                self._build_channel_credentials(),
                options=channel_opts,
            )
        else:
            self._channel = grpc.aio.insecure_channel(
                target,
                options=channel_opts,
            )
        _ensure_stubs()
        self._stub = _pb2_grpc.EngineServiceStub(self._channel)
        logger.info("Engine gRPC connected to %s (tls=%s)", target, self._tls)

    async def close(self) -> None:
        """Close the gRPC channel."""
        if self._channel:
            await self._channel.close()

    async def search(self, query: str, repo_id: str, top_k: int = 10) -> dict[str, Any]:
        """Run a semantic search over the indexed codebase.

        Args:
            query: Natural-language search query.
            repo_id: Repository identifier.
            top_k: Maximum number of ranked chunks to return.

        Returns:
            Dict with ``chunks`` (list of dicts with *content*, *file_path*,
            *score*, *start_line*, *end_line*, *language*) and ``fused_context``
            (pre-built RAG context string).
        """
        if not self._stub:
            await self.connect()

        request = _pb2.SearchRequest(
            query=query,
            repo_id=repo_id,
            config=_pb2.SearchConfig(top_k=top_k),
        )
        response = await self._stub.Search(request)

        chunks = []
        for chunk in response.chunks:
            chunks.append({
                "content": chunk.content,
                "file_path": chunk.file_path,
                "score": chunk.relevance_score,
                "start_line": chunk.start_line,
                "end_line": chunk.end_line,
                "language": chunk.language,
            })

        return {
            "chunks": chunks,
            "fused_context": response.fused_context if hasattr(response, "fused_context") else "",
        }

    async def get_index_status(self, repo_id: str) -> dict[str, Any]:
        """Check the indexing status for a repository.

        Returns:
            Dict with ``indexed`` (bool), ``total_chunks``, and ``total_files``.
        """
        if not self._stub:
            await self.connect()

        request = _pb2.IndexStatsRequest(repo_id=repo_id)
        response = await self._stub.GetIndexStats(request)

        stats = response.stats if response.found else None
        return {
            "indexed": response.found and stats is not None and stats.total_chunks > 0,
            "total_chunks": stats.total_chunks if stats else 0,
            "total_files": stats.total_files if stats else 0,
        }

    async def get_file_content(self, repo_id: str, file_path: str, ref: str = "") -> dict[str, Any]:
        """Read a file from the engine's local repository clone.

        Uses the ``GetFileContent`` RPC defined in ``engine.proto``.
        If the RPC is not yet compiled into the engine binary, the call
        degrades gracefully and returns an error message in the dict.

        Args:
            repo_id: Repository identifier.
            file_path: Relative path within the repository.
            ref: Optional git ref (branch/tag/SHA).  Empty means HEAD.

        Returns:
            Dict with ``content``, ``encoding``, ``is_binary``, and optionally
            ``error`` if the RPC is unavailable.
        """
        if not self._stub:
            await self.connect()

        try:
            request = _pb2.FileContentRequest(
                repo_id=repo_id,
                file_path=file_path,
                ref=ref,
            )
            response = await self._stub.GetFileContent(request)
            return {
                "content": response.content,
                "encoding": response.encoding,
                "is_binary": response.is_binary,
            }
        except (AttributeError, grpc.RpcError) as e:
            logger.warning("GetFileContent RPC not available yet: %s", e)
            return {
                "content": "",
                "encoding": "utf-8",
                "is_binary": False,
                "error": f"GetFileContent not implemented yet: {e}",
            }
