/**
 * AI PR Reviewer - Repository Scanner
 * 
 * Discovers and filters files in a repository for indexing.
 */

#include "indexer.h"
#include "types.h"
#include <filesystem>
#include <fstream>
#include <regex>
#include <algorithm>

namespace fs = std::filesystem;

namespace aipr {

namespace {

/**
 * Check if a path matches any pattern in the list
 */
bool matchesAnyPattern(const std::string& path, const std::vector<std::string>& patterns) {
    for (const auto& pattern : patterns) {
        // Simple glob-to-regex conversion
        std::string regex_pattern = pattern;
        
        // Escape special regex characters
        for (char c : {'\\', '.', '+', '?', '^', '$', '|', '(', ')', '[', ']', '{', '}'}) {
            size_t pos = 0;
            while ((pos = regex_pattern.find(c, pos)) != std::string::npos) {
                regex_pattern.insert(pos, "\\");
                pos += 2;
            }
        }
        
        // Convert glob wildcards
        size_t pos = 0;
        while ((pos = regex_pattern.find("\\*\\*", pos)) != std::string::npos) {
            regex_pattern.replace(pos, 4, ".*");
            pos += 2;
        }
        pos = 0;
        while ((pos = regex_pattern.find("\\*", pos)) != std::string::npos) {
            regex_pattern.replace(pos, 2, "[^/]*");
            pos += 5;
        }
        
        try {
            std::regex re(regex_pattern);
            if (std::regex_match(path, re)) {
                return true;
            }
        } catch (const std::regex_error&) {
            // Invalid pattern, skip
        }
    }
    return false;
}

/**
 * Detect if file is binary
 */
bool isBinaryFile(const std::string& path) {
    std::ifstream file(path, std::ios::binary);
    if (!file) return true;
    
    char buffer[1024];
    file.read(buffer, sizeof(buffer));
    auto bytes_read = file.gcount();
    
    // Check for null bytes (common in binary files)
    for (std::streamsize i = 0; i < bytes_read; ++i) {
        if (buffer[i] == '\0') {
            return true;
        }
    }
    
    return false;
}

/**
 * Count lines in a file
 */
size_t countLines(const std::string& path) {
    std::ifstream file(path);
    if (!file) return 0;
    
    size_t count = 0;
    std::string line;
    while (std::getline(file, line)) {
        ++count;
    }
    return count;
}

/**
 * Detect if file is auto-generated
 */
bool isGeneratedFile(const std::string& path, const std::string& content_preview) {
    // Check filename patterns
    static const std::vector<std::string> generated_patterns = {
        ".min.js", ".min.css", ".bundle.js",
        ".pb.go", ".pb.cc", ".pb.h", ".pb.java",
        "_pb2.py", ".generated.", ".g.dart",
        "package-lock.json", "yarn.lock", "Cargo.lock"
    };
    
    for (const auto& pattern : generated_patterns) {
        if (path.find(pattern) != std::string::npos) {
            return true;
        }
    }
    
    // Check content markers
    static const std::vector<std::string> generated_markers = {
        "// Code generated",
        "// DO NOT EDIT",
        "// @generated",
        "/* Auto-generated */",
        "# Generated by",
        "// AUTO-GENERATED"
    };
    
    for (const auto& marker : generated_markers) {
        if (content_preview.find(marker) != std::string::npos) {
            return true;
        }
    }
    
    return false;
}

} // anonymous namespace

/**
 * Repository scanner implementation
 */
class RepoScanner {
public:
    std::vector<FileInfo> scan(
        const std::string& repo_path,
        const IndexerConfig& config
    ) {
        std::vector<FileInfo> files;
        
        if (!fs::exists(repo_path) || !fs::is_directory(repo_path)) {
            return files;
        }
        
        const size_t max_size_bytes = config.max_file_size_kb * 1024;
        
        for (const auto& entry : fs::recursive_directory_iterator(
            repo_path,
            fs::directory_options::skip_permission_denied
        )) {
            if (!entry.is_regular_file()) {
                continue;
            }
            
            auto path = entry.path();
            auto relative_path = fs::relative(path, repo_path).string();
            
            // Normalize path separators
            std::replace(relative_path.begin(), relative_path.end(), '\\', '/');
            
            // Check exclude patterns
            if (matchesAnyPattern(relative_path, config.exclude_patterns)) {
                continue;
            }
            
            // Check include patterns (if specified)
            if (!config.include_patterns.empty() &&
                !matchesAnyPattern(relative_path, config.include_patterns)) {
                continue;
            }
            
            // Check file size
            auto file_size = entry.file_size();
            if (file_size > max_size_bytes) {
                continue;
            }
            
            // Create file info
            FileInfo info;
            info.path = relative_path;
            info.size_bytes = file_size;
            info.is_binary = isBinaryFile(path.string());
            
            if (info.is_binary) {
                continue;
            }
            
            // Read preview for generated file detection
            std::ifstream file(path);
            std::string preview;
            preview.resize(512);
            file.read(&preview[0], 512);
            preview.resize(static_cast<size_t>(file.gcount()));
            
            info.is_generated = isGeneratedFile(relative_path, preview);
            
            if (info.is_generated) {
                continue;  // Skip generated files by default
            }
            
            info.line_count = countLines(path.string());
            info.language = detectLanguage(relative_path);
            
            // Language filter
            if (!config.languages.empty()) {
                bool language_match = std::find(
                    config.languages.begin(),
                    config.languages.end(),
                    info.language
                ) != config.languages.end();
                
                if (!language_match) {
                    continue;
                }
            }
            
            files.push_back(std::move(info));
        }
        
        return files;
    }
    
private:
    std::string detectLanguage(const std::string& path) {
        // Get extension
        auto dot_pos = path.rfind('.');
        if (dot_pos == std::string::npos) {
            return "text";
        }
        
        std::string ext = path.substr(dot_pos);
        std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
        
        // Extension to language mapping
        static const std::unordered_map<std::string, std::string> ext_map = {
            {".cpp", "cpp"}, {".cc", "cpp"}, {".cxx", "cpp"}, {".c", "c"},
            {".h", "cpp"}, {".hpp", "cpp"}, {".hxx", "cpp"},
            {".java", "java"},
            {".py", "python"}, {".pyw", "python"},
            {".js", "javascript"}, {".mjs", "javascript"}, {".cjs", "javascript"},
            {".ts", "typescript"}, {".tsx", "typescript"}, {".jsx", "javascript"},
            {".go", "go"},
            {".rs", "rust"},
            {".rb", "ruby"},
            {".php", "php"},
            {".cs", "csharp"},
            {".swift", "swift"},
            {".kt", "kotlin"}, {".kts", "kotlin"},
            {".scala", "scala"},
            {".m", "objective-c"}, {".mm", "objective-c"},
            {".sh", "bash"}, {".bash", "bash"}, {".zsh", "bash"},
            {".ps1", "powershell"}, {".psm1", "powershell"},
            {".sql", "sql"},
            {".r", "r"}, {".R", "r"},
            {".lua", "lua"},
            {".pl", "perl"}, {".pm", "perl"},
            {".ex", "elixir"}, {".exs", "elixir"},
            {".erl", "erlang"}, {".hrl", "erlang"},
            {".clj", "clojure"}, {".cljs", "clojure"},
            {".hs", "haskell"},
            {".ml", "ocaml"}, {".mli", "ocaml"},
            {".fs", "fsharp"}, {".fsi", "fsharp"}, {".fsx", "fsharp"},
            {".dart", "dart"},
            {".vue", "vue"},
            {".svelte", "svelte"},
            {".json", "json"},
            {".yaml", "yaml"}, {".yml", "yaml"},
            {".xml", "xml"},
            {".html", "html"}, {".htm", "html"},
            {".css", "css"}, {".scss", "css"}, {".sass", "css"}, {".less", "css"},
            {".md", "markdown"}, {".markdown", "markdown"},
            {".rst", "rst"},
            {".txt", "text"},
            {".toml", "toml"},
            {".ini", "ini"}, {".cfg", "ini"},
            {".properties", "properties"},
            {".conf", "config"},
            {".env", "config"},
            {".resources", "properties"},
            {".dockerfile", "dockerfile"},
            {".tf", "terraform"}, {".tfvars", "terraform"},
            {".proto", "protobuf"},
            {".graphql", "graphql"}, {".gql", "graphql"},
        };
        
        // Check for special filenames
        auto filename = path.substr(path.rfind('/') + 1);
        if (filename == "Dockerfile" || filename.find("Dockerfile.") == 0) {
            return "dockerfile";
        }
        if (filename == "Makefile" || filename == "makefile") {
            return "makefile";
        }
        if (filename == "CMakeLists.txt") {
            return "cmake";
        }
        
        auto it = ext_map.find(ext);
        if (it != ext_map.end()) {
            return it->second;
        }
        
        return "text";
    }
};

} // namespace aipr
