# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import engine_pb2 as engine__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineServiceStub(object):
    """Main Engine Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexRepository = channel.unary_unary(
                '/aipr.engine.v1.EngineService/IndexRepository',
                request_serializer=engine__pb2.IndexRequest.SerializeToString,
                response_deserializer=engine__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.IndexRepositoryStream = channel.unary_stream(
                '/aipr.engine.v1.EngineService/IndexRepositoryStream',
                request_serializer=engine__pb2.IndexRequest.SerializeToString,
                response_deserializer=engine__pb2.IndexProgressUpdate.FromString,
                _registered_method=True)
        self.IncrementalIndex = channel.unary_unary(
                '/aipr.engine.v1.EngineService/IncrementalIndex',
                request_serializer=engine__pb2.IncrementalIndexRequest.SerializeToString,
                response_deserializer=engine__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.GetIndexStats = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetIndexStats',
                request_serializer=engine__pb2.IndexStatsRequest.SerializeToString,
                response_deserializer=engine__pb2.IndexStatsResponse.FromString,
                _registered_method=True)
        self.DeleteIndex = channel.unary_unary(
                '/aipr.engine.v1.EngineService/DeleteIndex',
                request_serializer=engine__pb2.DeleteIndexRequest.SerializeToString,
                response_deserializer=engine__pb2.DeleteIndexResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/aipr.engine.v1.EngineService/Search',
                request_serializer=engine__pb2.SearchRequest.SerializeToString,
                response_deserializer=engine__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.SearchStream = channel.unary_stream(
                '/aipr.engine.v1.EngineService/SearchStream',
                request_serializer=engine__pb2.SearchRequest.SerializeToString,
                response_deserializer=engine__pb2.ContextChunk.FromString,
                _registered_method=True)
        self.BuildReviewContext = channel.unary_unary(
                '/aipr.engine.v1.EngineService/BuildReviewContext',
                request_serializer=engine__pb2.ReviewContextRequest.SerializeToString,
                response_deserializer=engine__pb2.ReviewContextResponse.FromString,
                _registered_method=True)
        self.BuildReviewContextStream = channel.unary_stream(
                '/aipr.engine.v1.EngineService/BuildReviewContextStream',
                request_serializer=engine__pb2.ReviewContextRequest.SerializeToString,
                response_deserializer=engine__pb2.PREmbedProgressUpdate.FromString,
                _registered_method=True)
        self.RunHeuristics = channel.unary_unary(
                '/aipr.engine.v1.EngineService/RunHeuristics',
                request_serializer=engine__pb2.HeuristicsRequest.SerializeToString,
                response_deserializer=engine__pb2.HeuristicsResponse.FromString,
                _registered_method=True)
        self.ConfigureStorage = channel.unary_unary(
                '/aipr.engine.v1.EngineService/ConfigureStorage',
                request_serializer=engine__pb2.StorageConfigRequest.SerializeToString,
                response_deserializer=engine__pb2.StorageConfigResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/aipr.engine.v1.EngineService/HealthCheck',
                request_serializer=engine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=engine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetDiagnostics = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetDiagnostics',
                request_serializer=engine__pb2.DiagnosticsRequest.SerializeToString,
                response_deserializer=engine__pb2.DiagnosticsResponse.FromString,
                _registered_method=True)
        self.GetEmbedStats = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetEmbedStats',
                request_serializer=engine__pb2.EmbedStatsRequest.SerializeToString,
                response_deserializer=engine__pb2.EmbedStatsResponse.FromString,
                _registered_method=True)
        self.GetFileContent = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetFileContent',
                request_serializer=engine__pb2.FileContentRequest.SerializeToString,
                response_deserializer=engine__pb2.FileContentResponse.FromString,
                _registered_method=True)
        self.StreamEngineMetrics = channel.unary_stream(
                '/aipr.engine.v1.EngineService/StreamEngineMetrics',
                request_serializer=engine__pb2.EngineMetricsRequest.SerializeToString,
                response_deserializer=engine__pb2.EngineMetricsSnapshot.FromString,
                _registered_method=True)


class EngineServiceServicer(object):
    """Main Engine Service
    """

    def IndexRepository(self, request, context):
        """Indexing Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexRepositoryStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementalIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Retrieval Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildReviewContext(self, request, context):
        """Review Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildReviewContextStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunHeuristics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureStorage(self, request, context):
        """Configuration — API server pushes config to engine at startup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health & Diagnostics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedStats(self, request, context):
        """Embedding Statistics — per-repo embedding health and performance data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileContent(self, request, context):
        """File Content — read a file from the engine's local clone for the swarm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEngineMetrics(self, request, context):
        """Metrics — server-streaming so the Go API server can relay to the dashboard.
        The engine pushes a snapshot every interval_ms (default 1000).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexRepository,
                    request_deserializer=engine__pb2.IndexRequest.FromString,
                    response_serializer=engine__pb2.IndexResponse.SerializeToString,
            ),
            'IndexRepositoryStream': grpc.unary_stream_rpc_method_handler(
                    servicer.IndexRepositoryStream,
                    request_deserializer=engine__pb2.IndexRequest.FromString,
                    response_serializer=engine__pb2.IndexProgressUpdate.SerializeToString,
            ),
            'IncrementalIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementalIndex,
                    request_deserializer=engine__pb2.IncrementalIndexRequest.FromString,
                    response_serializer=engine__pb2.IndexResponse.SerializeToString,
            ),
            'GetIndexStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexStats,
                    request_deserializer=engine__pb2.IndexStatsRequest.FromString,
                    response_serializer=engine__pb2.IndexStatsResponse.SerializeToString,
            ),
            'DeleteIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIndex,
                    request_deserializer=engine__pb2.DeleteIndexRequest.FromString,
                    response_serializer=engine__pb2.DeleteIndexResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=engine__pb2.SearchRequest.FromString,
                    response_serializer=engine__pb2.SearchResponse.SerializeToString,
            ),
            'SearchStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchStream,
                    request_deserializer=engine__pb2.SearchRequest.FromString,
                    response_serializer=engine__pb2.ContextChunk.SerializeToString,
            ),
            'BuildReviewContext': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildReviewContext,
                    request_deserializer=engine__pb2.ReviewContextRequest.FromString,
                    response_serializer=engine__pb2.ReviewContextResponse.SerializeToString,
            ),
            'BuildReviewContextStream': grpc.unary_stream_rpc_method_handler(
                    servicer.BuildReviewContextStream,
                    request_deserializer=engine__pb2.ReviewContextRequest.FromString,
                    response_serializer=engine__pb2.PREmbedProgressUpdate.SerializeToString,
            ),
            'RunHeuristics': grpc.unary_unary_rpc_method_handler(
                    servicer.RunHeuristics,
                    request_deserializer=engine__pb2.HeuristicsRequest.FromString,
                    response_serializer=engine__pb2.HeuristicsResponse.SerializeToString,
            ),
            'ConfigureStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureStorage,
                    request_deserializer=engine__pb2.StorageConfigRequest.FromString,
                    response_serializer=engine__pb2.StorageConfigResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=engine__pb2.HealthCheckRequest.FromString,
                    response_serializer=engine__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiagnostics,
                    request_deserializer=engine__pb2.DiagnosticsRequest.FromString,
                    response_serializer=engine__pb2.DiagnosticsResponse.SerializeToString,
            ),
            'GetEmbedStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedStats,
                    request_deserializer=engine__pb2.EmbedStatsRequest.FromString,
                    response_serializer=engine__pb2.EmbedStatsResponse.SerializeToString,
            ),
            'GetFileContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileContent,
                    request_deserializer=engine__pb2.FileContentRequest.FromString,
                    response_serializer=engine__pb2.FileContentResponse.SerializeToString,
            ),
            'StreamEngineMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEngineMetrics,
                    request_deserializer=engine__pb2.EngineMetricsRequest.FromString,
                    response_serializer=engine__pb2.EngineMetricsSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aipr.engine.v1.EngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aipr.engine.v1.EngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineService(object):
    """Main Engine Service
    """

    @staticmethod
    def IndexRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/IndexRepository',
            engine__pb2.IndexRequest.SerializeToString,
            engine__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexRepositoryStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.EngineService/IndexRepositoryStream',
            engine__pb2.IndexRequest.SerializeToString,
            engine__pb2.IndexProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementalIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/IncrementalIndex',
            engine__pb2.IncrementalIndexRequest.SerializeToString,
            engine__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetIndexStats',
            engine__pb2.IndexStatsRequest.SerializeToString,
            engine__pb2.IndexStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/DeleteIndex',
            engine__pb2.DeleteIndexRequest.SerializeToString,
            engine__pb2.DeleteIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/Search',
            engine__pb2.SearchRequest.SerializeToString,
            engine__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.EngineService/SearchStream',
            engine__pb2.SearchRequest.SerializeToString,
            engine__pb2.ContextChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildReviewContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/BuildReviewContext',
            engine__pb2.ReviewContextRequest.SerializeToString,
            engine__pb2.ReviewContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildReviewContextStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.EngineService/BuildReviewContextStream',
            engine__pb2.ReviewContextRequest.SerializeToString,
            engine__pb2.PREmbedProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunHeuristics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/RunHeuristics',
            engine__pb2.HeuristicsRequest.SerializeToString,
            engine__pb2.HeuristicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/ConfigureStorage',
            engine__pb2.StorageConfigRequest.SerializeToString,
            engine__pb2.StorageConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/HealthCheck',
            engine__pb2.HealthCheckRequest.SerializeToString,
            engine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetDiagnostics',
            engine__pb2.DiagnosticsRequest.SerializeToString,
            engine__pb2.DiagnosticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetEmbedStats',
            engine__pb2.EmbedStatsRequest.SerializeToString,
            engine__pb2.EmbedStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetFileContent',
            engine__pb2.FileContentRequest.SerializeToString,
            engine__pb2.FileContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEngineMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.EngineService/StreamEngineMetrics',
            engine__pb2.EngineMetricsRequest.SerializeToString,
            engine__pb2.EngineMetricsSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
