# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import engine_pb2 as engine__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineServiceStub(object):
    """Main Engine Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexRepository = channel.unary_unary(
                '/aipr.engine.v1.EngineService/IndexRepository',
                request_serializer=engine__pb2.IndexRequest.SerializeToString,
                response_deserializer=engine__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.IndexRepositoryStream = channel.unary_stream(
                '/aipr.engine.v1.EngineService/IndexRepositoryStream',
                request_serializer=engine__pb2.IndexRequest.SerializeToString,
                response_deserializer=engine__pb2.IndexProgressUpdate.FromString,
                _registered_method=True)
        self.IncrementalIndex = channel.unary_unary(
                '/aipr.engine.v1.EngineService/IncrementalIndex',
                request_serializer=engine__pb2.IncrementalIndexRequest.SerializeToString,
                response_deserializer=engine__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.GetIndexStats = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetIndexStats',
                request_serializer=engine__pb2.IndexStatsRequest.SerializeToString,
                response_deserializer=engine__pb2.IndexStatsResponse.FromString,
                _registered_method=True)
        self.DeleteIndex = channel.unary_unary(
                '/aipr.engine.v1.EngineService/DeleteIndex',
                request_serializer=engine__pb2.DeleteIndexRequest.SerializeToString,
                response_deserializer=engine__pb2.DeleteIndexResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/aipr.engine.v1.EngineService/Search',
                request_serializer=engine__pb2.SearchRequest.SerializeToString,
                response_deserializer=engine__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.SearchStream = channel.unary_stream(
                '/aipr.engine.v1.EngineService/SearchStream',
                request_serializer=engine__pb2.SearchRequest.SerializeToString,
                response_deserializer=engine__pb2.ContextChunk.FromString,
                _registered_method=True)
        self.BuildReviewContext = channel.unary_unary(
                '/aipr.engine.v1.EngineService/BuildReviewContext',
                request_serializer=engine__pb2.ReviewContextRequest.SerializeToString,
                response_deserializer=engine__pb2.ReviewContextResponse.FromString,
                _registered_method=True)
        self.BuildReviewContextStream = channel.unary_stream(
                '/aipr.engine.v1.EngineService/BuildReviewContextStream',
                request_serializer=engine__pb2.ReviewContextRequest.SerializeToString,
                response_deserializer=engine__pb2.PREmbedProgressUpdate.FromString,
                _registered_method=True)
        self.RunHeuristics = channel.unary_unary(
                '/aipr.engine.v1.EngineService/RunHeuristics',
                request_serializer=engine__pb2.HeuristicsRequest.SerializeToString,
                response_deserializer=engine__pb2.HeuristicsResponse.FromString,
                _registered_method=True)
        self.ConfigureStorage = channel.unary_unary(
                '/aipr.engine.v1.EngineService/ConfigureStorage',
                request_serializer=engine__pb2.StorageConfigRequest.SerializeToString,
                response_deserializer=engine__pb2.StorageConfigResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/aipr.engine.v1.EngineService/HealthCheck',
                request_serializer=engine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=engine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetDiagnostics = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetDiagnostics',
                request_serializer=engine__pb2.DiagnosticsRequest.SerializeToString,
                response_deserializer=engine__pb2.DiagnosticsResponse.FromString,
                _registered_method=True)
        self.GetEmbedStats = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetEmbedStats',
                request_serializer=engine__pb2.EmbedStatsRequest.SerializeToString,
                response_deserializer=engine__pb2.EmbedStatsResponse.FromString,
                _registered_method=True)
        self.GetFileContent = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetFileContent',
                request_serializer=engine__pb2.FileContentRequest.SerializeToString,
                response_deserializer=engine__pb2.FileContentResponse.FromString,
                _registered_method=True)
        self.IngestAsset = channel.unary_unary(
                '/aipr.engine.v1.EngineService/IngestAsset',
                request_serializer=engine__pb2.IngestAssetRequest.SerializeToString,
                response_deserializer=engine__pb2.IngestAssetResponse.FromString,
                _registered_method=True)
        self.GetMultimodalConfig = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetMultimodalConfig',
                request_serializer=engine__pb2.GetMultimodalConfigRequest.SerializeToString,
                response_deserializer=engine__pb2.GetMultimodalConfigResponse.FromString,
                _registered_method=True)
        self.ConfigureMultimodal = channel.unary_unary(
                '/aipr.engine.v1.EngineService/ConfigureMultimodal',
                request_serializer=engine__pb2.ConfigureMultimodalRequest.SerializeToString,
                response_deserializer=engine__pb2.ConfigureMultimodalResponse.FromString,
                _registered_method=True)
        self.DownloadModel = channel.unary_stream(
                '/aipr.engine.v1.EngineService/DownloadModel',
                request_serializer=engine__pb2.ConfigureMultimodalRequest.SerializeToString,
                response_deserializer=engine__pb2.ModelDownloadProgress.FromString,
                _registered_method=True)
        self.StreamEngineMetrics = channel.unary_stream(
                '/aipr.engine.v1.EngineService/StreamEngineMetrics',
                request_serializer=engine__pb2.EngineMetricsRequest.SerializeToString,
                response_deserializer=engine__pb2.EngineMetricsSnapshot.FromString,
                _registered_method=True)
        self.GetRepoFileMap = channel.unary_unary(
                '/aipr.engine.v1.EngineService/GetRepoFileMap',
                request_serializer=engine__pb2.RepoFileMapRequest.SerializeToString,
                response_deserializer=engine__pb2.RepoFileMapResponse.FromString,
                _registered_method=True)


class EngineServiceServicer(object):
    """Main Engine Service
    """

    def IndexRepository(self, request, context):
        """Indexing Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexRepositoryStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementalIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Retrieval Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildReviewContext(self, request, context):
        """Review Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildReviewContextStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunHeuristics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureStorage(self, request, context):
        """Configuration — API server pushes config to engine at startup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health & Diagnostics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedStats(self, request, context):
        """Embedding Statistics — per-repo embedding health and performance data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileContent(self, request, context):
        """File Content — read a file from the engine's local clone for the swarm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestAsset(self, request, context):
        """Asset Ingestion — embed documents, PDFs, images, audio, and URL content into a repo index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMultimodalConfig(self, request, context):
        """Multimodal Embedding Configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureMultimodal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEngineMetrics(self, request, context):
        """Metrics — server-streaming so the Go API server can relay to the dashboard.
        The engine pushes a snapshot every interval_ms (default 1000).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRepoFileMap(self, request, context):
        """Knowledge Graph — retrieve the intra-repo file/symbol dependency map.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexRepository,
                    request_deserializer=engine__pb2.IndexRequest.FromString,
                    response_serializer=engine__pb2.IndexResponse.SerializeToString,
            ),
            'IndexRepositoryStream': grpc.unary_stream_rpc_method_handler(
                    servicer.IndexRepositoryStream,
                    request_deserializer=engine__pb2.IndexRequest.FromString,
                    response_serializer=engine__pb2.IndexProgressUpdate.SerializeToString,
            ),
            'IncrementalIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementalIndex,
                    request_deserializer=engine__pb2.IncrementalIndexRequest.FromString,
                    response_serializer=engine__pb2.IndexResponse.SerializeToString,
            ),
            'GetIndexStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexStats,
                    request_deserializer=engine__pb2.IndexStatsRequest.FromString,
                    response_serializer=engine__pb2.IndexStatsResponse.SerializeToString,
            ),
            'DeleteIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIndex,
                    request_deserializer=engine__pb2.DeleteIndexRequest.FromString,
                    response_serializer=engine__pb2.DeleteIndexResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=engine__pb2.SearchRequest.FromString,
                    response_serializer=engine__pb2.SearchResponse.SerializeToString,
            ),
            'SearchStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchStream,
                    request_deserializer=engine__pb2.SearchRequest.FromString,
                    response_serializer=engine__pb2.ContextChunk.SerializeToString,
            ),
            'BuildReviewContext': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildReviewContext,
                    request_deserializer=engine__pb2.ReviewContextRequest.FromString,
                    response_serializer=engine__pb2.ReviewContextResponse.SerializeToString,
            ),
            'BuildReviewContextStream': grpc.unary_stream_rpc_method_handler(
                    servicer.BuildReviewContextStream,
                    request_deserializer=engine__pb2.ReviewContextRequest.FromString,
                    response_serializer=engine__pb2.PREmbedProgressUpdate.SerializeToString,
            ),
            'RunHeuristics': grpc.unary_unary_rpc_method_handler(
                    servicer.RunHeuristics,
                    request_deserializer=engine__pb2.HeuristicsRequest.FromString,
                    response_serializer=engine__pb2.HeuristicsResponse.SerializeToString,
            ),
            'ConfigureStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureStorage,
                    request_deserializer=engine__pb2.StorageConfigRequest.FromString,
                    response_serializer=engine__pb2.StorageConfigResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=engine__pb2.HealthCheckRequest.FromString,
                    response_serializer=engine__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiagnostics,
                    request_deserializer=engine__pb2.DiagnosticsRequest.FromString,
                    response_serializer=engine__pb2.DiagnosticsResponse.SerializeToString,
            ),
            'GetEmbedStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedStats,
                    request_deserializer=engine__pb2.EmbedStatsRequest.FromString,
                    response_serializer=engine__pb2.EmbedStatsResponse.SerializeToString,
            ),
            'GetFileContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileContent,
                    request_deserializer=engine__pb2.FileContentRequest.FromString,
                    response_serializer=engine__pb2.FileContentResponse.SerializeToString,
            ),
            'IngestAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestAsset,
                    request_deserializer=engine__pb2.IngestAssetRequest.FromString,
                    response_serializer=engine__pb2.IngestAssetResponse.SerializeToString,
            ),
            'GetMultimodalConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMultimodalConfig,
                    request_deserializer=engine__pb2.GetMultimodalConfigRequest.FromString,
                    response_serializer=engine__pb2.GetMultimodalConfigResponse.SerializeToString,
            ),
            'ConfigureMultimodal': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureMultimodal,
                    request_deserializer=engine__pb2.ConfigureMultimodalRequest.FromString,
                    response_serializer=engine__pb2.ConfigureMultimodalResponse.SerializeToString,
            ),
            'DownloadModel': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=engine__pb2.ConfigureMultimodalRequest.FromString,
                    response_serializer=engine__pb2.ModelDownloadProgress.SerializeToString,
            ),
            'StreamEngineMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEngineMetrics,
                    request_deserializer=engine__pb2.EngineMetricsRequest.FromString,
                    response_serializer=engine__pb2.EngineMetricsSnapshot.SerializeToString,
            ),
            'GetRepoFileMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepoFileMap,
                    request_deserializer=engine__pb2.RepoFileMapRequest.FromString,
                    response_serializer=engine__pb2.RepoFileMapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aipr.engine.v1.EngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aipr.engine.v1.EngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineService(object):
    """Main Engine Service
    """

    @staticmethod
    def IndexRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/IndexRepository',
            engine__pb2.IndexRequest.SerializeToString,
            engine__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexRepositoryStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.EngineService/IndexRepositoryStream',
            engine__pb2.IndexRequest.SerializeToString,
            engine__pb2.IndexProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementalIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/IncrementalIndex',
            engine__pb2.IncrementalIndexRequest.SerializeToString,
            engine__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetIndexStats',
            engine__pb2.IndexStatsRequest.SerializeToString,
            engine__pb2.IndexStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/DeleteIndex',
            engine__pb2.DeleteIndexRequest.SerializeToString,
            engine__pb2.DeleteIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/Search',
            engine__pb2.SearchRequest.SerializeToString,
            engine__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.EngineService/SearchStream',
            engine__pb2.SearchRequest.SerializeToString,
            engine__pb2.ContextChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildReviewContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/BuildReviewContext',
            engine__pb2.ReviewContextRequest.SerializeToString,
            engine__pb2.ReviewContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildReviewContextStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.EngineService/BuildReviewContextStream',
            engine__pb2.ReviewContextRequest.SerializeToString,
            engine__pb2.PREmbedProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunHeuristics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/RunHeuristics',
            engine__pb2.HeuristicsRequest.SerializeToString,
            engine__pb2.HeuristicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/ConfigureStorage',
            engine__pb2.StorageConfigRequest.SerializeToString,
            engine__pb2.StorageConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/HealthCheck',
            engine__pb2.HealthCheckRequest.SerializeToString,
            engine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetDiagnostics',
            engine__pb2.DiagnosticsRequest.SerializeToString,
            engine__pb2.DiagnosticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetEmbedStats',
            engine__pb2.EmbedStatsRequest.SerializeToString,
            engine__pb2.EmbedStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetFileContent',
            engine__pb2.FileContentRequest.SerializeToString,
            engine__pb2.FileContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/IngestAsset',
            engine__pb2.IngestAssetRequest.SerializeToString,
            engine__pb2.IngestAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMultimodalConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetMultimodalConfig',
            engine__pb2.GetMultimodalConfigRequest.SerializeToString,
            engine__pb2.GetMultimodalConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureMultimodal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/ConfigureMultimodal',
            engine__pb2.ConfigureMultimodalRequest.SerializeToString,
            engine__pb2.ConfigureMultimodalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.EngineService/DownloadModel',
            engine__pb2.ConfigureMultimodalRequest.SerializeToString,
            engine__pb2.ModelDownloadProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEngineMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.EngineService/StreamEngineMetrics',
            engine__pb2.EngineMetricsRequest.SerializeToString,
            engine__pb2.EngineMetricsSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRepoFileMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.EngineService/GetRepoFileMap',
            engine__pb2.RepoFileMapRequest.SerializeToString,
            engine__pb2.RepoFileMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CrossRepoServiceStub(object):
    """============================================================================
    Cross-Repo Service

    A SEPARATE service for all cross-repo operations. This is intentionally NOT
    added to EngineService to maintain single-repo isolation guarantees.
    The Go server handles authorization via crossrepo.Authorizer BEFORE calling
    any of these RPCs.
    ============================================================================

    Dependency Graph ─────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRepoManifest = channel.unary_unary(
                '/aipr.engine.v1.CrossRepoService/GetRepoManifest',
                request_serializer=engine__pb2.RepoManifestRequest.SerializeToString,
                response_deserializer=engine__pb2.RepoManifestResponse.FromString,
                _registered_method=True)
        self.GetCrossRepoDependencies = channel.unary_unary(
                '/aipr.engine.v1.CrossRepoService/GetCrossRepoDependencies',
                request_serializer=engine__pb2.CrossRepoDepsRequest.SerializeToString,
                response_deserializer=engine__pb2.CrossRepoDepsResponse.FromString,
                _registered_method=True)
        self.BuildDependencyGraph = channel.unary_unary(
                '/aipr.engine.v1.CrossRepoService/BuildDependencyGraph',
                request_serializer=engine__pb2.BuildDepGraphRequest.SerializeToString,
                response_deserializer=engine__pb2.BuildDepGraphResponse.FromString,
                _registered_method=True)
        self.FederatedSearch = channel.unary_unary(
                '/aipr.engine.v1.CrossRepoService/FederatedSearch',
                request_serializer=engine__pb2.FederatedSearchRequest.SerializeToString,
                response_deserializer=engine__pb2.FederatedSearchResponse.FromString,
                _registered_method=True)
        self.FederatedSearchStream = channel.unary_stream(
                '/aipr.engine.v1.CrossRepoService/FederatedSearchStream',
                request_serializer=engine__pb2.FederatedSearchRequest.SerializeToString,
                response_deserializer=engine__pb2.FederatedContextChunk.FromString,
                _registered_method=True)


class CrossRepoServiceServicer(object):
    """============================================================================
    Cross-Repo Service

    A SEPARATE service for all cross-repo operations. This is intentionally NOT
    added to EngineService to maintain single-repo isolation guarantees.
    The Go server handles authorization via crossrepo.Authorizer BEFORE calling
    any of these RPCs.
    ============================================================================

    Dependency Graph ─────────────────────────────────────────
    """

    def GetRepoManifest(self, request, context):
        """GetRepoManifest returns the structural manifest for a single repo
        (build system, primary language, modules, repo type). The engine already
        computes this during indexing; this RPC exposes it read-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrossRepoDependencies(self, request, context):
        """GetCrossRepoDependencies resolves inter-repo import/dependency edges.
        Given a source repo, returns all symbols or packages that reference
        artifacts belonging to other repos in the same org.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildDependencyGraph(self, request, context):
        """BuildDependencyGraph constructs the full org-level dependency graph
        across all linked repos. Heavy operation — intended for background jobs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FederatedSearch(self, request, context):
        """Federated Search ─────────────────────────────────────────

        FederatedSearch fans out a query across multiple repo indices and returns
        merged, score-normalized results. The Go server pre-filters the target
        repo list through crossrepo.Authorizer. This is a SEPARATE RPC from
        EngineService.Search which operates on a single repo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FederatedSearchStream(self, request, context):
        """FederatedSearchStream is the streaming variant of FederatedSearch.
        Chunks are streamed as they are found across repos, ordered by score.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrossRepoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRepoManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepoManifest,
                    request_deserializer=engine__pb2.RepoManifestRequest.FromString,
                    response_serializer=engine__pb2.RepoManifestResponse.SerializeToString,
            ),
            'GetCrossRepoDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrossRepoDependencies,
                    request_deserializer=engine__pb2.CrossRepoDepsRequest.FromString,
                    response_serializer=engine__pb2.CrossRepoDepsResponse.SerializeToString,
            ),
            'BuildDependencyGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildDependencyGraph,
                    request_deserializer=engine__pb2.BuildDepGraphRequest.FromString,
                    response_serializer=engine__pb2.BuildDepGraphResponse.SerializeToString,
            ),
            'FederatedSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.FederatedSearch,
                    request_deserializer=engine__pb2.FederatedSearchRequest.FromString,
                    response_serializer=engine__pb2.FederatedSearchResponse.SerializeToString,
            ),
            'FederatedSearchStream': grpc.unary_stream_rpc_method_handler(
                    servicer.FederatedSearchStream,
                    request_deserializer=engine__pb2.FederatedSearchRequest.FromString,
                    response_serializer=engine__pb2.FederatedContextChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aipr.engine.v1.CrossRepoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aipr.engine.v1.CrossRepoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrossRepoService(object):
    """============================================================================
    Cross-Repo Service

    A SEPARATE service for all cross-repo operations. This is intentionally NOT
    added to EngineService to maintain single-repo isolation guarantees.
    The Go server handles authorization via crossrepo.Authorizer BEFORE calling
    any of these RPCs.
    ============================================================================

    Dependency Graph ─────────────────────────────────────────
    """

    @staticmethod
    def GetRepoManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.CrossRepoService/GetRepoManifest',
            engine__pb2.RepoManifestRequest.SerializeToString,
            engine__pb2.RepoManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCrossRepoDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.CrossRepoService/GetCrossRepoDependencies',
            engine__pb2.CrossRepoDepsRequest.SerializeToString,
            engine__pb2.CrossRepoDepsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildDependencyGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.CrossRepoService/BuildDependencyGraph',
            engine__pb2.BuildDepGraphRequest.SerializeToString,
            engine__pb2.BuildDepGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FederatedSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipr.engine.v1.CrossRepoService/FederatedSearch',
            engine__pb2.FederatedSearchRequest.SerializeToString,
            engine__pb2.FederatedSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FederatedSearchStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipr.engine.v1.CrossRepoService/FederatedSearchStream',
            engine__pb2.FederatedSearchRequest.SerializeToString,
            engine__pb2.FederatedContextChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
