// RTVortex Engine gRPC Service Definition
// This defines the communication protocol between the API Server and C++ Engine

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.0
// source: engine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_IndexRepository_FullMethodName          = "/aipr.engine.v1.EngineService/IndexRepository"
	EngineService_IndexRepositoryStream_FullMethodName    = "/aipr.engine.v1.EngineService/IndexRepositoryStream"
	EngineService_IncrementalIndex_FullMethodName         = "/aipr.engine.v1.EngineService/IncrementalIndex"
	EngineService_GetIndexStats_FullMethodName            = "/aipr.engine.v1.EngineService/GetIndexStats"
	EngineService_DeleteIndex_FullMethodName              = "/aipr.engine.v1.EngineService/DeleteIndex"
	EngineService_Search_FullMethodName                   = "/aipr.engine.v1.EngineService/Search"
	EngineService_SearchStream_FullMethodName             = "/aipr.engine.v1.EngineService/SearchStream"
	EngineService_BuildReviewContext_FullMethodName       = "/aipr.engine.v1.EngineService/BuildReviewContext"
	EngineService_BuildReviewContextStream_FullMethodName = "/aipr.engine.v1.EngineService/BuildReviewContextStream"
	EngineService_RunHeuristics_FullMethodName            = "/aipr.engine.v1.EngineService/RunHeuristics"
	EngineService_ConfigureStorage_FullMethodName         = "/aipr.engine.v1.EngineService/ConfigureStorage"
	EngineService_HealthCheck_FullMethodName              = "/aipr.engine.v1.EngineService/HealthCheck"
	EngineService_GetDiagnostics_FullMethodName           = "/aipr.engine.v1.EngineService/GetDiagnostics"
	EngineService_GetFileContent_FullMethodName           = "/aipr.engine.v1.EngineService/GetFileContent"
	EngineService_StreamEngineMetrics_FullMethodName      = "/aipr.engine.v1.EngineService/StreamEngineMetrics"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Main Engine Service
type EngineServiceClient interface {
	// Indexing Operations
	IndexRepository(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	IndexRepositoryStream(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexProgressUpdate], error)
	IncrementalIndex(ctx context.Context, in *IncrementalIndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	GetIndexStats(ctx context.Context, in *IndexStatsRequest, opts ...grpc.CallOption) (*IndexStatsResponse, error)
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
	// Retrieval Operations
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchStream(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContextChunk], error)
	// Review Operations
	BuildReviewContext(ctx context.Context, in *ReviewContextRequest, opts ...grpc.CallOption) (*ReviewContextResponse, error)
	BuildReviewContextStream(ctx context.Context, in *ReviewContextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PREmbedProgressUpdate], error)
	RunHeuristics(ctx context.Context, in *HeuristicsRequest, opts ...grpc.CallOption) (*HeuristicsResponse, error)
	// Configuration — API server pushes config to engine at startup
	ConfigureStorage(ctx context.Context, in *StorageConfigRequest, opts ...grpc.CallOption) (*StorageConfigResponse, error)
	// Health & Diagnostics
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetDiagnostics(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error)
	// File Content — read a file from the engine's local clone for the swarm
	GetFileContent(ctx context.Context, in *FileContentRequest, opts ...grpc.CallOption) (*FileContentResponse, error)
	// Metrics — server-streaming so the Go API server can relay to the dashboard.
	// The engine pushes a snapshot every interval_ms (default 1000).
	StreamEngineMetrics(ctx context.Context, in *EngineMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EngineMetricsSnapshot], error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) IndexRepository(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, EngineService_IndexRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) IndexRepositoryStream(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[0], EngineService_IndexRepositoryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IndexRequest, IndexProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_IndexRepositoryStreamClient = grpc.ServerStreamingClient[IndexProgressUpdate]

func (c *engineServiceClient) IncrementalIndex(ctx context.Context, in *IncrementalIndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, EngineService_IncrementalIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetIndexStats(ctx context.Context, in *IndexStatsRequest, opts ...grpc.CallOption) (*IndexStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexStatsResponse)
	err := c.cc.Invoke(ctx, EngineService_GetIndexStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIndexResponse)
	err := c.cc.Invoke(ctx, EngineService_DeleteIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, EngineService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) SearchStream(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContextChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[1], EngineService_SearchStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, ContextChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_SearchStreamClient = grpc.ServerStreamingClient[ContextChunk]

func (c *engineServiceClient) BuildReviewContext(ctx context.Context, in *ReviewContextRequest, opts ...grpc.CallOption) (*ReviewContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewContextResponse)
	err := c.cc.Invoke(ctx, EngineService_BuildReviewContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) BuildReviewContextStream(ctx context.Context, in *ReviewContextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PREmbedProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[2], EngineService_BuildReviewContextStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReviewContextRequest, PREmbedProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_BuildReviewContextStreamClient = grpc.ServerStreamingClient[PREmbedProgressUpdate]

func (c *engineServiceClient) RunHeuristics(ctx context.Context, in *HeuristicsRequest, opts ...grpc.CallOption) (*HeuristicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeuristicsResponse)
	err := c.cc.Invoke(ctx, EngineService_RunHeuristics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ConfigureStorage(ctx context.Context, in *StorageConfigRequest, opts ...grpc.CallOption) (*StorageConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageConfigResponse)
	err := c.cc.Invoke(ctx, EngineService_ConfigureStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, EngineService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetDiagnostics(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticsResponse)
	err := c.cc.Invoke(ctx, EngineService_GetDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetFileContent(ctx context.Context, in *FileContentRequest, opts ...grpc.CallOption) (*FileContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileContentResponse)
	err := c.cc.Invoke(ctx, EngineService_GetFileContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) StreamEngineMetrics(ctx context.Context, in *EngineMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EngineMetricsSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[3], EngineService_StreamEngineMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EngineMetricsRequest, EngineMetricsSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_StreamEngineMetricsClient = grpc.ServerStreamingClient[EngineMetricsSnapshot]

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
//
// Main Engine Service
type EngineServiceServer interface {
	// Indexing Operations
	IndexRepository(context.Context, *IndexRequest) (*IndexResponse, error)
	IndexRepositoryStream(*IndexRequest, grpc.ServerStreamingServer[IndexProgressUpdate]) error
	IncrementalIndex(context.Context, *IncrementalIndexRequest) (*IndexResponse, error)
	GetIndexStats(context.Context, *IndexStatsRequest) (*IndexStatsResponse, error)
	DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
	// Retrieval Operations
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchStream(*SearchRequest, grpc.ServerStreamingServer[ContextChunk]) error
	// Review Operations
	BuildReviewContext(context.Context, *ReviewContextRequest) (*ReviewContextResponse, error)
	BuildReviewContextStream(*ReviewContextRequest, grpc.ServerStreamingServer[PREmbedProgressUpdate]) error
	RunHeuristics(context.Context, *HeuristicsRequest) (*HeuristicsResponse, error)
	// Configuration — API server pushes config to engine at startup
	ConfigureStorage(context.Context, *StorageConfigRequest) (*StorageConfigResponse, error)
	// Health & Diagnostics
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetDiagnostics(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error)
	// File Content — read a file from the engine's local clone for the swarm
	GetFileContent(context.Context, *FileContentRequest) (*FileContentResponse, error)
	// Metrics — server-streaming so the Go API server can relay to the dashboard.
	// The engine pushes a snapshot every interval_ms (default 1000).
	StreamEngineMetrics(*EngineMetricsRequest, grpc.ServerStreamingServer[EngineMetricsSnapshot]) error
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) IndexRepository(context.Context, *IndexRequest) (*IndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexRepository not implemented")
}
func (UnimplementedEngineServiceServer) IndexRepositoryStream(*IndexRequest, grpc.ServerStreamingServer[IndexProgressUpdate]) error {
	return status.Error(codes.Unimplemented, "method IndexRepositoryStream not implemented")
}
func (UnimplementedEngineServiceServer) IncrementalIndex(context.Context, *IncrementalIndexRequest) (*IndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementalIndex not implemented")
}
func (UnimplementedEngineServiceServer) GetIndexStats(context.Context, *IndexStatsRequest) (*IndexStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndexStats not implemented")
}
func (UnimplementedEngineServiceServer) DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIndex not implemented")
}
func (UnimplementedEngineServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedEngineServiceServer) SearchStream(*SearchRequest, grpc.ServerStreamingServer[ContextChunk]) error {
	return status.Error(codes.Unimplemented, "method SearchStream not implemented")
}
func (UnimplementedEngineServiceServer) BuildReviewContext(context.Context, *ReviewContextRequest) (*ReviewContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildReviewContext not implemented")
}
func (UnimplementedEngineServiceServer) BuildReviewContextStream(*ReviewContextRequest, grpc.ServerStreamingServer[PREmbedProgressUpdate]) error {
	return status.Error(codes.Unimplemented, "method BuildReviewContextStream not implemented")
}
func (UnimplementedEngineServiceServer) RunHeuristics(context.Context, *HeuristicsRequest) (*HeuristicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunHeuristics not implemented")
}
func (UnimplementedEngineServiceServer) ConfigureStorage(context.Context, *StorageConfigRequest) (*StorageConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureStorage not implemented")
}
func (UnimplementedEngineServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedEngineServiceServer) GetDiagnostics(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiagnostics not implemented")
}
func (UnimplementedEngineServiceServer) GetFileContent(context.Context, *FileContentRequest) (*FileContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileContent not implemented")
}
func (UnimplementedEngineServiceServer) StreamEngineMetrics(*EngineMetricsRequest, grpc.ServerStreamingServer[EngineMetricsSnapshot]) error {
	return status.Error(codes.Unimplemented, "method StreamEngineMetrics not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call panics, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_IndexRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).IndexRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_IndexRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).IndexRepository(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_IndexRepositoryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IndexRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).IndexRepositoryStream(m, &grpc.GenericServerStream[IndexRequest, IndexProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_IndexRepositoryStreamServer = grpc.ServerStreamingServer[IndexProgressUpdate]

func _EngineService_IncrementalIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementalIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).IncrementalIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_IncrementalIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).IncrementalIndex(ctx, req.(*IncrementalIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetIndexStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetIndexStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetIndexStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetIndexStats(ctx, req.(*IndexStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_DeleteIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).DeleteIndex(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_SearchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).SearchStream(m, &grpc.GenericServerStream[SearchRequest, ContextChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_SearchStreamServer = grpc.ServerStreamingServer[ContextChunk]

func _EngineService_BuildReviewContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).BuildReviewContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_BuildReviewContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).BuildReviewContext(ctx, req.(*ReviewContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_BuildReviewContextStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReviewContextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).BuildReviewContextStream(m, &grpc.GenericServerStream[ReviewContextRequest, PREmbedProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_BuildReviewContextStreamServer = grpc.ServerStreamingServer[PREmbedProgressUpdate]

func _EngineService_RunHeuristics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeuristicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).RunHeuristics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_RunHeuristics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).RunHeuristics(ctx, req.(*HeuristicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ConfigureStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ConfigureStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ConfigureStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ConfigureStorage(ctx, req.(*StorageConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetDiagnostics(ctx, req.(*DiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetFileContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetFileContent(ctx, req.(*FileContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_StreamEngineMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EngineMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).StreamEngineMetrics(m, &grpc.GenericServerStream[EngineMetricsRequest, EngineMetricsSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_StreamEngineMetricsServer = grpc.ServerStreamingServer[EngineMetricsSnapshot]

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aipr.engine.v1.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexRepository",
			Handler:    _EngineService_IndexRepository_Handler,
		},
		{
			MethodName: "IncrementalIndex",
			Handler:    _EngineService_IncrementalIndex_Handler,
		},
		{
			MethodName: "GetIndexStats",
			Handler:    _EngineService_GetIndexStats_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _EngineService_DeleteIndex_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _EngineService_Search_Handler,
		},
		{
			MethodName: "BuildReviewContext",
			Handler:    _EngineService_BuildReviewContext_Handler,
		},
		{
			MethodName: "RunHeuristics",
			Handler:    _EngineService_RunHeuristics_Handler,
		},
		{
			MethodName: "ConfigureStorage",
			Handler:    _EngineService_ConfigureStorage_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _EngineService_HealthCheck_Handler,
		},
		{
			MethodName: "GetDiagnostics",
			Handler:    _EngineService_GetDiagnostics_Handler,
		},
		{
			MethodName: "GetFileContent",
			Handler:    _EngineService_GetFileContent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IndexRepositoryStream",
			Handler:       _EngineService_IndexRepositoryStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchStream",
			Handler:       _EngineService_SearchStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BuildReviewContextStream",
			Handler:       _EngineService_BuildReviewContextStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEngineMetrics",
			Handler:       _EngineService_StreamEngineMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "engine.proto",
}
